### ISSUE TITLE
CreateToolhelp32Snapshot failed

### ISSUE THREAD

**Issue by thesuavehog** [imphasing/dockerPatcher#1]
I'm not sure which docker process to patch as there are a few running when I look at the Get-Process list....
```
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    130      11    20784      12128             16164   0 com.docker.backend
    133      12    21616      20460       0.16  15412   1 com.docker.proxy
    713      41    65372      75964              4624   0 com.docker.service
    815      65    87428     105956       2.86  16864   1 Docker Desktop
     36       3      500       2204              4412   0 Docker.Watchguard
    241      17    27444      36180              8504   0 dockerd
```

I'm also not sure if I'm supposed to use 'p' or 'u' in the command line but I tried both (no difference in the result).

sometimes I get "cannot find vmcompute.dll in the target process", so I assume that process is not one to patch.

but I either get that message or 'CreateToolhelp32Snapshot failed'

Examples:
```
> .\patchDocker.exe p 16864
cannot find vmcompute.dll in the target process
> .\patchDocker.exe p 8504
CreateToolhelp32Snapshot failed
> .\patchDocker.exe u 8504
CreateToolhelp32Snapshot failed
> .\patchDocker.exe p 16164
CreateToolhelp32Snapshot failed
> .\patchDocker.exe p 15412
cannot find vmcompute.dll in the target process
> .\patchDocker.exe u 16164
CreateToolhelp32Snapshot failed
> .\patchDocker.exe u 4624
CreateToolhelp32Snapshot failed
> .\patchDocker.exe p 4624
CreateToolhelp32Snapshot failed
```

Windows Version:
```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
```

**Comment by imphasing** [comment]
I am on 10.0.18362.418

Are there any pending Windows updates on your machine? MS recently patched and it changed vmcompute.dll slightly so I commented out the old code in the .c file

You might try using that commented out code here: https://github.com/imphasing/dockerPatcher/blob/master/patchDocker/patchDocker.c#L44 and comment out the current check_integrity_bytes - that's how the offending code in vmcompute.dll is found

The correct process to patch is dockerd - I updated the README to include a line about how to run it, you just do patchDocker.exe p (ps dockerd).id

**Comment by imphasing** [comment]
Also, are you on 64 bit? Everything in this is hardcoded for 64 bit so if you're not it might cause issues

**Comment by imphasing** [comment]
https://stackoverflow.com/questions/26474349/createtoolhelp32snapshot-invalid-handle-value-error-partial-copy

I would guess you're somehow calling this from 32 bit, try making sure you call it from 64 bit powershell to verify - that's how I do it
